# Generated by Django 3.0.6 on 2020-05-21 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_customuser_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='available',
            field=models.BooleanField(default=False),
        ),
    ]
